//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwCorretor
    {
        public string CPF_do_a__Corretor_a_ { get; set; }
        public string RG_do_a__Corretor_a_ { get; set; }
        public string Nome_Completo { get; set; }
        public string Sexo { get; set; }
        public string Imobiliaria_Vinculado { get; set; }
        public string Telefone_da_loja { get; set; }
        public string Telefone_2 { get; set; }
        public string Celular { get; set; }
        public string Telefone_comercial { get; set; }
        public string Telefone_extra { get; set; }
        public string R__Av__do_endereço { get; set; }
        public Nullable<int> Número_do_endereço { get; set; }
        public string Complemento_do_endereço { get; set; }
        public string Bairro_do_imóvel { get; set; }
        public string Cidade_do_imóvel { get; set; }
        public string Estado_do_imóvel { get; set; }
    }
}
