//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwDespachante
    {
        public string Nome_do_Despachante { get; set; }
        public Nullable<decimal> Preço_do_Despachante { get; set; }
        public Nullable<short> Serviços_já_realizados { get; set; }
        public Nullable<short> Serviços_Pendentes { get; set; }
        public string Telefone_do_Despachante { get; set; }
        public string Telefone_2_do_Despachante { get; set; }
        public string Celular_do_Despachante { get; set; }
        public string Telefone_comercial_do_Despachante { get; set; }
        public string Telefone_extra_do_Despachante { get; set; }
        public string R__Av__do_endereço { get; set; }
        public Nullable<int> Número_do_endereço { get; set; }
        public string Complemento_do_endereço { get; set; }
        public string Bairro_do_imóvel { get; set; }
        public string Cidade_do_imóvel { get; set; }
        public string Estado_do_imóvel { get; set; }
    }
}
