//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwImobiliaria
    {
        public string Creci_da_Imobiliaria { get; set; }
        public string Nome_do_CEO { get; set; }
        public System.DateTime Data_da_emissão_CRECI { get; set; }
        public string Razão_social { get; set; }
        public string Nome_da_loja { get; set; }
        public string Telefone_da_loja { get; set; }
        public string Telefone_2 { get; set; }
        public string Celular { get; set; }
        public string Telefone_comercial { get; set; }
        public string Telefone_extra { get; set; }
        public string Sócio_Majoritário { get; set; }
        public string Sócio_Senior { get; set; }
        public string R__Av__do_endereço { get; set; }
        public Nullable<int> Número_do_endereço { get; set; }
        public string Complemento_do_endereço { get; set; }
        public string Bairro_do_imóvel { get; set; }
        public string Cidade_do_imóvel { get; set; }
        public string Estado_do_imóvel { get; set; }
    }
}
