//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class vwImovel
    {
        public int Registro_do_Imóvel { get; set; }
        public string Frente_do_Imóvel { get; set; }
        public string Lado_do_Imóvel { get; set; }
        public int Capitador_do_Imóvel { get; set; }
        public string Proprietário_do_Imóvel { get; set; }
        public string R__Av__do_endereço { get; set; }
        public Nullable<int> Número_do_endereço { get; set; }
        public string Complemento_do_endereço { get; set; }
        public string Bairro_do_imóvel { get; set; }
        public string Cidade_do_imóvel { get; set; }
        public string Estado_do_imóvel { get; set; }
    }
}
